# Generated by Django 4.2.7 on 2025-11-05 10:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Period Report')], default='daily', help_text='Type of performance report', max_length=20)),
                ('report_date', models.DateField(help_text='Date for which the report is generated')),
                ('start_date', models.DateField(help_text='Start date of the reporting period')),
                ('end_date', models.DateField(help_text='End date of the reporting period')),
                ('productivity_score', models.FloatField(default=0.0, help_text='Calculated productivity score (0-100)')),
                ('attendance_percentage', models.FloatField(default=0.0, help_text='Attendance percentage for the period')),
                ('total_active_time', models.DurationField(default=datetime.timedelta(0), help_text='Total active time during the period')),
                ('total_idle_time', models.DurationField(default=datetime.timedelta(0), help_text='Total idle time during the period')),
                ('login_count', models.IntegerField(default=0, help_text='Number of login sessions')),
                ('devices_used', models.IntegerField(default=0, help_text='Number of different devices used')),
                ('detailed_metrics', models.TextField(blank=True, help_text='JSON formatted detailed metrics and breakdowns')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the report was generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the report was updated')),
                ('user', models.ForeignKey(help_text='User for whom the report is generated', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Report',
                'verbose_name_plural': 'Performance Reports',
                'ordering': ['-report_date', '-generated_at'],
                'indexes': [models.Index(fields=['user', 'report_date'], name='productivit_user_id_65c9bf_idx'), models.Index(fields=['report_type', 'report_date'], name='productivit_report__2e61e1_idx')],
                'unique_together': {('user', 'report_type', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('web_browsing', 'Web Browsing'), ('application_usage', 'Application Usage'), ('file_access', 'File Access'), ('idle', 'Idle Time'), ('active', 'Active Usage'), ('other', 'Other')], help_text='Type of activity performed', max_length=20)),
                ('duration', models.DurationField(help_text='Duration of the activity')),
                ('resources_accessed', models.TextField(blank=True, help_text='JSON formatted list of resources accessed (URLs, applications, files)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity occurred')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping related activities', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which activity originated', null=True)),
                ('device', models.ForeignKey(help_text='Device used for the activity', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='devices.device')),
                ('user', models.ForeignKey(help_text='User who performed the activity', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='productivit_user_id_04cd2b_idx'), models.Index(fields=['device', 'timestamp'], name='productivit_device__b6413f_idx'), models.Index(fields=['activity_type', 'timestamp'], name='productivit_activit_af075b_idx')],
            },
        ),
    ]
