# Generated by Django 4.2.7 on 2025-11-05 10:31

import devices.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Device name (e.g., 'John's MacBook Pro')", max_length=100)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('tablet', 'Tablet'), ('smartphone', 'Smartphone'), ('desktop', 'Desktop'), ('other', 'Other')], help_text='Type of device', max_length=20)),
                ('mac_address', models.CharField(help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, unique=True, validators=[devices.models.validate_mac_address])),
                ('operating_system', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('ios', 'iOS'), ('android', 'Android'), ('other', 'Other')], help_text='Operating system of the device', max_length=20)),
                ('compliance_status', models.BooleanField(default=False, help_text='Whether device meets security requirements')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='When the device was first registered')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time device was active on network')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time device information was updated')),
                ('user', models.ForeignKey(help_text='Owner of the device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
