# Generated by Django 4.2.7 on 2025-11-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='access_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Current access status of the device', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='registered_by',
            field=models.ForeignKey(help_text='User who registered this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeviceAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the access request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the access request was created')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved or rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the request')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved or rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(help_text='The device requesting access', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='devices.device')),
                ('requester', models.ForeignKey(help_text='User who registered the device', on_delete=django.db.models.deletion.CASCADE, related_name='device_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Access Request',
                'verbose_name_plural': 'Device Access Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('access_request', 'Device Access Request'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, help_text='Related access request if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='devices.deviceaccessrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='devices_not_recipie_665a0d_idx'), models.Index(fields=['related_request'], name='devices_not_related_79c006_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deviceaccessrequest',
            index=models.Index(fields=['status', 'requested_at'], name='devices_dev_status_6c728c_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccessrequest',
            index=models.Index(fields=['requester', 'status'], name='devices_dev_request_7915c4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccessrequest',
            index=models.Index(fields=['device'], name='devices_dev_device__d1e333_idx'),
        ),
    ]
