# Generated by Django 4.2.7 on 2025-11-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='When the session started')),
                ('logout_time', models.DateTimeField(blank=True, help_text='When the session ended', null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Last recorded activity in this session')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the session')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('violation', 'Security Violation')], default='active', help_text='Current status of the session', max_length=20)),
                ('violation_count', models.PositiveIntegerField(default=0, help_text='Number of security violations in this session')),
                ('violation_details', models.TextField(blank=True, help_text='JSON string containing violation details')),
                ('device', models.ForeignKey(help_text='Device used for this session', on_delete=django.db.models.deletion.CASCADE, related_name='session_tracks', to='devices.device')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='session_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Tracker',
                'verbose_name_plural': 'Session Trackers',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='security_se_user_id_73a79b_idx'), models.Index(fields=['device', 'status'], name='security_se_device__e6a5c0_idx'), models.Index(fields=['session_key'], name='security_se_session_81020c_idx'), models.Index(fields=['login_time'], name='security_se_login_t_9e0f86_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Administrator')], help_text='User role this access control applies to', max_length=20)),
                ('allowed_domains', models.TextField(blank=True, default='[]', help_text='JSON list of allowed domains for this role')),
                ('blocked_domains', models.TextField(blank=True, default='[]', help_text='JSON list of blocked domains for this role')),
                ('time_restrictions', models.TextField(blank=True, default='{}', help_text='JSON object with time-based access restrictions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this access control rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this rule was last updated')),
                ('created_by', models.ForeignKey(help_text='Administrator who created this rule', on_delete=django.db.models.deletion.CASCADE, related_name='created_access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control Rule',
                'verbose_name_plural': 'Access Control Rules',
                'ordering': ['-created_at'],
                'unique_together': {('role',)},
            },
        ),
    ]
